### ISSUE TITLE
Need to update ZFS documentation

### ISSUE THREAD

**Issue by johnsonw** [intel-hpdd/Online-Help#17]
The ZFS instructions have a changed a bit and need to be updated. Tom and I discussed this earlier and he stated the following:

- All `zpool create` commands need to have `-o multihost=on`
- need `hostid` in monitored mode context
- after creating pools , they need to be exported from all hosts attached to the storage
- manually importing/exporting/administration  of zpools is best done before servers are added or when agents are stopped to avoid any undesired interaction by the agents
- the output from `zpool import` will be different with mmp from that shown (output shown is with multihost=off, default is off. multihost==multimount/mmp)
- references to import -f also need to be removed as it is no longer possible with MMP enabled
- the output from commands when MMP is enabled is different on an already occupied pool

**Comment by johnsonw** [comment]
PDF showing the current ZFS page:
[online_help_zfs.pdf](https://github.com/intel-hpdd/Online-Help/files/1335009/online_help_zfs.pdf)

**Comment by brianjmurrell** [comment]
> manually importing/exporting/administration of zpools is best done before servers are added or when agents are stopped to avoid any undesired interaction by the agents

Is this not now fully protected by MMP?  Are there still gaps where users can shoot themselves in the foot?

**Comment by jgrund** [comment]
> Is this not now fully protected by MMP? Are there still gaps where users can shoot themselves in the foot?

I imagine it's because the agents will periodically import / export pools and that may interfere with trying to import and work with them, and vice-versa.

Of course, once we no longer import pools, this will be moot.

**Comment by brianjmurrell** [comment]
> I imagine it's because the agents will periodically import / export pools and that may interfere with trying to import and work with them, and vice-versa.

Understood.  What I was asking though is that won't MMP always prevent IML and the user from stepping on each others' toes?  Won't one get an error if the other has a device in use, because of MMP?

**Comment by jgrund** [comment]
A change to the above for 4.1. once pools are created they should remain imported.
