### ISSUE TITLE
Create docs on how to build

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/Online-Help#27]
What are the prerequisites to building IML?

- clone repo
- install the YUM Copr plugin:
```
yum -y install yum-plugin-copr
```
- install the manager-for-lustre and DNF YUM repositories:

```
# yum copr enable managerforlustre/manager-for-lustre
# yum copr enable ngompa/dnf-el7
```
- install needed software:
```
# yum -y install python-virtualenv systemd-devel postgresql-devel graphviz-devel createrepo epel-release npm python-sphinx python-django gcc
```

How does one build IML?
```
$ make
```

Probably more details to come as tickets are filed.

**Comment by kbuggenhout** [comment]
you may want to add to that, if you start from CentOS7 development workstation, you only need to add the repo's, and subsequently you have to add npm , yum install -y npm ( after epel was enabled). otherwise make will fail with npm not found.

**Comment by kbuggenhout** [comment]
some more things I needed to add ( not been able to successfully compile yet) 
sudo yum install python-sphinx python-django

**Comment by jn0** [comment]
Please, take `iml-prereq.sh` from https://github.com/intel-hpdd/intel-manager-for-lustre/issues/343#issuecomment-336921917  it does the job.

**Comment by kbuggenhout** [comment]
with the current commands I get a decent build, after removing the .storage_server.repo.
tested with a fresh install of CentOS 7.4 with development package group ( yum group install "Development Tools") which takes care of most of the packages you need ( except npm)

got all artifacts built, including the install tarbal.. :)
