### ISSUE TITLE
Document process to make tarball release

### ISSUE THREAD

**Issue by jgrund** [intel-hpdd/Online-Help#29]
Description

Jira ticket "CentOS 7 build problems #343" worked out the process of making the software.

Intel ML install instructions start with IML-4.0.0.0.tar (a tarball software release) but this is not produced by the make process.

Please document how to make the release tarball

Repro

Follow the needed steps to make from git and observe there is no release tarball as described as the starting point for installation of software.

Version

What version of IML? IML current Master + commit c12fb35 + commit 6c7f7cb

What Operating System? Centos 7.4
What Operating System version? Centos 7.4

**Comment by brianjmurrell** [comment]
Isn't `chroma-bundles/iml-<version>.tar.gz` what is being asked for here?

**Comment by Kmannth** [comment]
Thanks for the update.  I missed the tarball in chrome-bundles.

**Comment by brianjmurrell** [comment]
Awesome.  Glad it's what you are looking for.
