### ISSUE TITLE
is there documentation to adapt branding ?

### ISSUE THREAD

**Issue by kbuggenhout** [intel-hpdd/Online-Help#30]
is there a way to add branding or framework artwork to the current build without breaking it?

I am writing storage plugins to function with DellEMC storage arrays. to interogate the arrays and get information on location, path to the drives.

**Comment by jgrund** [comment]
Hi @kbuggenhout,

Could you let us know which part of the GUI you'd like theming support for? 

Thanks much,

Joe

**Comment by jgrund** [comment]
Going to close this due to inactivity. Please feel free to reopen if you'd like to discuss further.
