### ISSUE TITLE
Documentation for upgrade from 2.x community edition to IML and 2.10.x LTS

### ISSUE THREAD

**Issue by CanWood** [intel-hpdd/Online-Help#45]
Hi folks,

Our infrastructure is currently based on The [2.7.0 Intel distributed binaries](https://downloads.hpdd.intel.com/public/lustre/lustre-2.7.0/el6/server/RPMS/x86_64/) and a roll-your-own pacemaker/corosync configuration.  While the documentation for migrating from IEEL 2.4 to latest IML and LTS is [covered well](https://intel-hpdd.github.io/Online-Help/docs/Upgrade_Guide/Upgrade_EE-2.4-el6_to_LU-LTS-el7.html) (thank you), is there any documentation regarding provisioning an IML over top of an existing  community edition install?

To be clear, we recognize the need for the OS upgrade from CentOS6 to CentOS7 and do not expect to do it hot.  We'd plan an outage.  Also, our HA stack does not match the configuration that IEEL and IML use, so that would likely need completely replacing.  All we'd want to ensure we maintain is the contents of our MGT, MDT, and 48 OSSs, the file system itself.  We're open to replacing all other configs.

Cheers!

**Comment by johnsonw** [comment]
Hi @CanWood ,

Thank you for your feedback. I'm glad to hear your are looking to upgrade to the latest version of IML. This upgrade will require that you will be using Lustre@2.10.x. Will upgrading to this version of Lustre be an issue?

**Comment by CanWood** [comment]
More than happy to upgrade to 2.10.x.  That's actually what prompted this. I figured a single outage to upgrade the lustre infrastructure while dropping the IML layer on top would be a good idea.  To clarify, I'm not looking to upgrade IML.  I don't have it in place yet.  I'm looking to know whether or not there is a safe, documented procedure to install IML and bring in existing OSTs, MGT, and MDT. 

As we'd be replacing all OSes, hence all network and multipath config, and all HA definitions, I'd expect that the details of our current config shouldn't play much of a role in the process.  We would need to add a management network, as our current HA traffic and lustre traffic are on the same interfaces, but that should be no trouble.

Cheers

**Comment by johnsonw** [comment]
Hi @CanWood, I think your best option is to upgrade your system, Lustre, network / multipath configuration, etc as you would normally. Once the upgrade is complete, you can look at installing IML in **monitored mode**.  This will allow you to use your existing setup, which manages your existing filesystem. To do this, you would install IML after you finish upgrading your system and all of its components. You would then add each of your servers, selecting the **Monitored** profile. This will install the agent software on each of your servers but it will not attempt to manage them. Does this make sense?

Regards,

Will

**Comment by CanWood** [comment]
Thanks, Will,


That makes perfect sense.  I wasn't aware of the monitored mode.  I'll give it a run on my testbed first.  Thanks for sending me down the right path.


Cheers!


________________________________

**Comment by johnsonw** [comment]
Hi @CanWood, thanks again for reaching out to us. I just wanted to follow up and see how the process is going. If you run into any issues please feel free to reach out to us. Thanks! 

Regards,

Will

**Comment by CanWood** [comment]
Afternoon, Will.  At this point, it's looking like we likely won't opt to install IML.  Our current network and HA configuration seems different enough that rolling the upgrade of the Lustre components in with a fundamental overhaul of all architecture to match the IML requirements seems like biting off a bit more than would be safe for one outage.

I do see in the docs that Monitor mode is supported when the HA stack does not match the HA spec, so I'm presuming we could investigate installing after the fact.  So that'll be the plan: Upgrade lustre, then test IML on the testbed to see how it plays with a "not to spec" system, then decide.

Thanks for the guidance and feedback on this.  As you've answered my original question, I'll mark this issue as closed.  Cheers!
